[platformio]
default_envs = light

[env:Nodes]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<Nodes.cpp>


[env:light]
extends = env:Nodes
build_flags =
    -D NODE_LIGHT
    -D NODE_ID=0x60
    -D TRANS_SLOT_MS=20000
