[env:gateway]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 19200
src_filter = +<*> -<Nodes.cpp>
lib_deps = 
    https://github.com/jpmeijers/RN2483-Arduino-Library.git

[env:Nodes]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
src_filter = +<Nodes.cpp>

[env:thermostat]
extends = env:Nodes
build_flags =
    -D NO_BATTERY
    -D NODE_THERMOSTAT
    -D NODE_ID=0x20
    -D TRANS_SLOT_MS=10000

[env:light]
extends = env:Nodes
build_flags =
    -D NO_BATTERY
    -D NODE_LIGHT
    -D NODE_ID=0x80
    -D TRANS_SLOT_MS=20000

[env:lock]
extends = env:Nodes
build_flags =
    -D NO_BATTERY
    -D NODE_LOCK
    -D NODE_ID=0x40
    -D TRANS_SLOT_MS=30000
