[env:gateway]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 19200
src_filter = +<*> -<Nodes.cpp>

[env:Nodes]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
src_filter = +<*> -<Gateway.cpp>
